apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 8888           # The port exposed by the Service
    targetPort: 80      # The port inside the phpmyadmin container
    nodePort: 30009     # Optional: Node port for external access (for NodePort type)
  #type: NodePort         # Change to ClusterIP or LoadBalancer as needed
  type: LoadBalancer
