apiVersion: v1
kind: Service
metadata:
  name: web
  annotations: 
    cloud.google.com/load-balancer-type: "External"
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30005
  #type: NodePort
  type: LoadBalancer
  loadBalancerIP: 35.206.97.188

