name: "GKE Infra Provisioning"

on:
  push:
    paths:
      - 'terraform/GCP/**'
    branches:
      - pipelinetest
  workflow_dispatch:

env:
  TF_VAR_gcp_project_id: folkloric-byway-461621-h0
  TF_VAR_gcp_region: us-central1

jobs:
  terraform:
    name: "Terraform GKE Plan & Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/GCP

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -no-color -out=tfplan.out

      # - name: Terraform Apply (only if plan has changes)
      #   if: steps.tf-plan.outputs.stdout != '' && github.ref == 'refs/heads/main'
      #   run: terraform apply -auto-approve tfplan.out
