name: Terraform GKE Plan & Apply

on:
  push:
    branches:
      - pipelinetest
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan and Apply for GKE
    runs-on: ubuntu-latest

    env:
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_gcp_region: ${{ secrets.GCP_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: terraform/GCP

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/GCP

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
        working-directory: terraform/GCP

      - name: Upload plan JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-json
          path: terraform/GCP/tfplan.json

      - name: Detect changes in plan
        id: detect
        run: |
          if grep -q '"changesPresent": true' terraform/GCP/tfplan.json; then
            echo "CHANGES=true" >> $GITHUB_ENV
          else
            echo "CHANGES=false" >> $GITHUB_ENV
          fi

      - name: Terraform Apply
      #   if: env.CHANGES == 'true'
        run: terraform apply -auto-approve tfplan.binary
        working-directory: terraform/GCP
