name: Conditional Multi-Cloud Velero Backup with Rclone

on:
  push:
    branches:
      - velvobackuptest

jobs:
  determine-cluster:
    runs-on: ubuntu-latest
    outputs:
      selected-cluster: ${{ steps.resolve.outputs.cluster }}
    steps:
      - name: Resolve DNS and set output
        id: resolve
        run: |
          IP=$(nslookup multiclouddr.trafficmanager.net | grep 'Address:' | tail -n1 | awk '{print $2}')
          echo "Resolved IP: $IP"
          if [ "$IP" == "4.246.216.66" ]; then
            echo "cluster=aks" >> "$GITHUB_OUTPUT"
          elif [ "$IP" == "35.188.36.154" ]; then
            echo "cluster=gke" >> "$GITHUB_OUTPUT"
          else
            echo "Unknown IP resolved: $IP"
            exit 1
          fi

  aks-backup:
    name: Debug Aks Backup Job
    needs: determine-cluster
    # Uncomment when ready to conditionally trigger
    # if: needs.determine-cluster.outputs.selected-cluster == 'aks'
    runs-on: ubuntu-latest
    steps:
      - name: Print confirm AKS backup should run
        run: |
          echo "selected-cluster is: ${{ needs.determine-cluster.outputs.selected-cluster }}"

  gke-backup:
    name: Debug GKE Backup Job
    needs: determine-cluster
    # Uncomment when ready to conditionally trigger
    # if: needs.determine-cluster.outputs.selected-cluster == 'gke'
    runs-on: ubuntu-latest
    steps:
      - name: Print confirm GKE backup should run
        run: |
          echo "selected-cluster is: ${{ needs.determine-cluster.outputs.selected-cluster }}"
