name: Conditional Multi-Cloud Velero Backup with Rclone

on:
  push:
    branches:
      - velvobackuptest
jobs:
  determine-cluster:
    runs-on: ubuntu-latest
    outputs:
      selected-cluster: ${{ steps.set-output.outputs.cluster }}
    steps:
      - name: Resolve DNS
        id: resolve
        run: |
          IP=$(nslookup multiclouddr.trafficmanager.net | grep 'Address:' | tail -n1 | awk '{print $2}')
          echo "Resolved IP: $IP"
          if [ "$IP" == "4.246.216.66" ]; then
            echo "cluster=aks" >> $GITHUB_OUTPUT
          elif [ "$IP" == "35.188.36.154" ]; then
            echo "cluster=gke" >> $GITHUB_OUTPUT
          else
            echo "Unknown IP resolved: $IP"
            exit 1
          fi
        shell: bash

      - name: Set output
        id: set-target
        run: echo "target=${{ steps.check-dns.outputs.target }}"
        shell: bash

  aks-backup:
    needs: determine-cluster
    if: needs.determine-cluster.outputs.selected-cluster == 'aks'
    uses: ./.github/workflows/AKS-VeleroBackupAndRclone.yml
    secrets: inherit

  gke-backup:
    needs: determine-cluster
    if: needs.determine-cluster.outputs.selected-cluster == 'gke'
    uses: ./.github/workflows/GKE-VeleroBackupAndRclone.yml
    secrets: inherit