on:
  push:
    branches:
      - pipelinetest
  workflow_dispatch:

permissions:
  contents: read
  issues: write
 
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://multiclouddr.trafficmanager.net'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
