apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: atugroup1/phpmyadmin:20250301171801
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: "database"
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          value: "mysql"     # The MySQL user
        - name: PMA_PASSWORD
          value: "HelloDublin"  # The MySQL password
        ports:
         - containerPort: 80
           protocol: TCP
        resources: {}
status: {}
